accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/Bye.html'), name="logout"),
    path('success/', views.SuccessLoginView.as_view(), name="success"),
    path('user/', views.userprofile, name='user'),
    path('user/edit/', views.update_profile, name='editProfile'),
    path('user/password/', views.change_password, name='changePassword')
]

gamepage/urls.py
from django.urls import path
from post import views
from gamepage import views

app_name = 'gamepage'

urlpatterns = [
]

post/urls.py
from django.urls import path, include

import gamepage
from post import views

app_name = 'post'

urlpatterns = [
    path('add/', views.PostCreateView.as_view(), name='add-post'),
    path('allpost/', views.post_list, name='all-post'),
    path('allpost/<int:pk>/', views.post_detail, name='detail'),
    path('allpost/<int:pk>/', views.post_favourite, name='favourite'),
    path('allpost/<tag_slug>/', views.post_by_tag, name='tagged_post'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from post.models import Post


class UserProfile(User):
    profile_pic = models.ImageField(upload_to='profile_img')
    profile_phone = models.CharField(max_length=12)

    def __str__(self):
        return self.username

gamepage/models.py
from django.db import models
from accounts.models import UserProfile


# Create your models here.

class GamePage(models.Model):
    gameTitle = models.CharField(max_length=255)
    text = models.TextField()
    date_created = models.DateField(auto_now_add=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.gameTitle

post/models.py
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    date_created = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='game_img', default='default value')
    gameLink = models.CharField(max_length=500, default='add link')
    tags = TaggableManager(blank=True)
    favourite = models.ManyToManyField(User, related_name='favourite_post', null=True, blank=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from accounts.models import UserProfile


class UserProfileForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ('username', 'first_name', 'last_name',
                  'password1', 'password2',
                  'email')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'email'
        )

post/forms.py
from django import forms
from post.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'gameLink', 'text', 'tags']

accounts/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from accounts import models, forms
from django.urls import reverse_lazy

# Create your views here.
from accounts.forms import EditProfileForm
from post.models import Post


def index(request):
    return render(request, 'home.html')


def main(request):
    posts = Post.objects.all()
    return render(request, 'main.html', {'posts': posts})


class ByeView(generic.TemplateView):
    template_name = 'accounts/Bye.html'


class SuccessLoginView(generic.TemplateView):
    template_name = 'accounts/success.html'


class UserCreateView(generic.CreateView):
    model = models.UserProfile
    form_class = forms.UserProfileForm
    template_name = 'accounts/register.html'
    extra_context = {'my_form': form_class}
    success_url = reverse_lazy('main')


def userprofile(request):
    user = request.user
    user_posts = Post.objects.filter(author=request.user).order_by('-date_created')
    template = 'accounts/user.html'
    return render(request, template, {'user_posts': user_posts, 'user': user})


def update_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('accounts:user')
        else:
            return redirect('accounts:editProfile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'my_form': form}
        return render(request, 'accounts/update_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:user')
        else:
            return redirect('accounts:changePassword')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

gamepage/views.py
from django.shortcuts import render


# Create your views here.

post/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from taggit.models import Tag

from post import models, forms
from django.urls import reverse_lazy

# Create your views here.
from .models import Post


class PostCreateView(generic.CreateView):
    model = models.Post
    form_class = forms.PostForm
    template_name = 'post/postcreate.html'
    success_url = reverse_lazy('main')

    def form_valid(self, form):
        form.instance.author = self.request.user.userprofile
        form.save(commit=True)
        return super(PostCreateView, self).form_valid(form)


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'post/main.html', {'posts': posts})


def post_by_tag(request, tag_slug):
    tag = Tag.objects.get(slug=tag_slug)
    posts = Post.objects.filter(tags__name=tag)
    context = {
        'tag': tag,
        'posts': posts
    }
    return render(request, 'post/postlist.html', context)


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    if post.favourite.filter(id=request.user.id).exists():
        is_favorite = True
    else:
        is_favorite = False

    return render(request, 'post/postbase.html', {'post': post})


def post_favourite(request, pk):
    post = Post.objects.get(pk=pk)
    if post.favourite.filter(pk=request.user.id).exists():
        is_favorite = True
        post.favourite.remove(request.user)
    else:
        is_favorite = False
        post.favourite.add(request.user)

    return render(request, 'post:detail', {'post': post})

'''
            if request.method == 'POST':
        favourite = post
        user = request.user
        user.favorites.add(favourite)
        if post.favourite.filter(id=request.user.id).exists():
            is_favorite = True
            post.favourite.remove(request.user)
        else:
            is_favorite = False
            post.favourite.add(request.user)
        '''

"""
class PostDetailView(generic.DeleteView):
    model = models.Post
    context_object_name = 'post'
    template_name = 'post/postbase.html'
    
class PostListView(generic.ListView):
    model = models.Post
    context_object_name = 'posts'
    template_name = 'post/postlist.html'
"""

accounts/templates/accounts/Bye.html
{% extends 'register_base.html' %}
{%  load static %}

{% block content %}
    <style>
        .screen img{
            width:500px;
            height: 400px;
            border-radius: 35%;
        }
        .bye{
            position: absolute;
            font-family: 'Press Start 2P', cursive;
            color: #c8deff;
            font-size: 200%;
            bottom:28%;
            left: 32%;
            text-align: center;
            line-height: 1.6;
        }
        a{
            color: #c8deff;
            text-decoration: none;
        }
    </style>

    <img src="{% static 'images/space.gif' %}">
    <div class="bye"><a href="/main" title="RETURN TO MAIN">See<br>You<br>Again</a></div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'register_base.html' %}
{%  load static %}
{% block content %}
    <style>
        .loginScreen{
            color: #c8deff;
            padding: 10px 40px;
            position: absolute;
            bottom: 13%;
        }
    </style>
    <div class="loginScreen">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

                <input type="submit" value="Login"
                       style="letter-spacing: 0px;
                       width: 90px;background: rgb(115,158,225);
                       color: #fff; float: left; padding: 5px;
                       font-family: 'Press Start 2P', cursive;">
                <input type="hidden" name="next" value="{% url 'accounts:success' %}">
                <br><br>
                <p>If you do not have an account, please, click <a href="{% url 'accounts:register' %}">here</a></p>
        </form>
    </div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'register_base.html' %}
{%  load static %}
{% block content %}
    <style>
    .regScreen{
        width: 450px;
        height: 300px;
        color: #c8deff;
        padding: 10px 40px;
        position: absolute;
        bottom: 20%;
    }
    .helptext, li{
        display: none;
    }
    </style>
    <div class="regScreen">
        <h1>Registration</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ my_form.as_p }}
            <input type="submit" value="Register" style="letter-spacing: 0px;
                       width: 120px;background: rgb(115,158,225);
                       color: #fff; float: left; padding: 5px;
                       font-family: 'Press Start 2P', cursive;">
            <a href="{% url 'accounts:login' %}" title="if you have account">

                <button type="button" style="letter-spacing: 0px;
                       width: 90px;background: rgb(115,158,225);
                       color: #fff; float: left; padding: 5px;
                       font-family: 'Press Start 2P', cursive;
                        float: right;">
                    Login
                </button>
            </a>
        <br>
        <br>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

                <style>

                    #profileTop{
                        background: #076283;
                        width: 900px;
                        height: 250px;
                        margin: 50px auto 0;
                        opacity: 95%;
	                    border: 10px solid rgba(0, 255 , 255, 0.5);
                        border-bottom: none;
                    }
                    .person {
                        width: 160px;
                        margin: 25px 40px;
                        background-size: cover;
                        float: left;
                        text-transform: uppercase;
                        text-align: center;
                    }
                    .person p{
                        font-family: 'Press Start 2P', cursive;
                        font-size: 80%;
                        color: #4fe5e5;
                        background-color: #0d0e47;
                    }
                    #ava{
                        width: 160px;
                        height: 155px;
                        background-size: cover;
                        float: left;
                        overflow: hidden;
                        border: 5px solid #0d0e47;
                    }
                    #ava img{
                        width: 150px;
                        height: auto;
                        background-color: #ffffff;
                    }
                    #description{
                        width: 250px;
                        height: 150px;
                        margin: 25px 5px;
                        float: left;
                    }
                    .leftPart{
                        margin: 8px 0;
                        padding: 8px 0;
                    }
                    .rightPart{
                        width: 250px;
                        height: 150px;
                        margin: 25px 40px;
                        float: right;
                    }
                    #editProfile{
                        background-color: #4fe5e5;
                        color: white;
                        padding: 10px 30px;
                        text-align: center;
                        text-decoration: none;
                        display: inline-block;
                        font-size: 16px;
                        margin: 20px 20px 20px 35%;
                        cursor: pointer;
                    }
                    #profileBottom{
                        background: rgba(24,34, 91, 0.9);
                        width: 900px;
                        margin: 0 auto;
	                    border: 10px solid rgba(0, 255 , 255, 0.5);
                        border-top: none;
                    }
                    h3{
                        height: 50px;
                        padding: 40px;
                    }
                    #achievements{
                        width: 100%;
                        height: 50px;
                    }
                    .firstBlock{
                        margin-left: 40px;
                    }
                    .block{
                        width: 50px;
                        height: 50px;
                        background: #a59fdd;
                        float: left;
                        margin-right: 25px;
                    }
                    #listFavGames{
                        width: 100%;
                    }
                    .scroll, .scroll1{
                        width: 90%;
                        text-align: center;
                        margin: 5%;
                        display: inline-block;
                    }
                    #userPosts{
                        width: 90%;
                        height: 160px;
                        margin: auto;
                        overflow: hidden;
                        white-space:nowrap;
                    }
                    #slideLeft,
                    #slideRight, #slideLeft1,
                    #slideRight1 {
                        display: inline-block;
                        border-radius: 100%;
                        padding: 5px;
                        background-color: rgba(219, 47 , 0, 0.9);
                    }
                    .gameItem{
                        position: relative;
                        background-color: rgba(165, 159, 221, 0.8);
                        border-radius: 15px;
                        padding: 5px;
                        text-align: center;
                        display: inline-block;
                        width: 120px;
                        height: 140px;
                        margin: 10px;
                    }
                    .gameItem img{
                        width:110px;
                        height: 110px;
                        border-radius: 15px;
                        border: 2px solid #0d0e47;
                    }
                    .gameItem p{
                        font-family: 'Fredoka One', cursive;
                        color: #0d0e47;
                        overflow: hidden;
                    }
                    h1, h2, h3, h4, h5, p, .nickname, .empty{
                        font-family: 'Press Start 2P', cursive;
                    }
                    .empty a{
                        font-family: 'Press Start 2P', cursive;
                        color: rgba(219, 47 , 0, 0.9);
                        text-transform: uppercase;
                    }
                </style>

		<main>

                <div id="profileTop">
                    <div class="person">
                        <div id="ava">
                            {% if user.userprofile.profile_pic.url %}
                                <img src="{{ user.userprofile.profile_pic.url }}">
                            {% else %}
                                <img src="{% static 'images/noavatar.png' %}">
                            {%  endif %}
                        </div>
                        <p>{{ user.first_name }} {{ user.last_name }}</p>
                    </div>

                    <div id="description">
                        <span class="nickname leftPart" style="font-size: 30px;">{{user.username}}</span>
                        <p class="leftPart">
                            Status: Zadrotina
                        </p>
                        <span class="email leftPart">{{user.email}}</span>
                    </div>

                    <div class="rightPart">
                        <a href="{% url 'accounts:editProfile' %}" title="Edit Profile">
                            <button id="editProfile" style="margin-left: 5%; margin-top: 20%">Edit profile</button>
                        </a>
                    </div>

                </div>

                <div id="profileBottom">
                    <div class="profileBottomContent">
                        <h3>Achievements</h3>
                        <div id="achievements">
                            <div class="achieve firstBlock block"></div>
                            <div class="achieve block"></div>
                            <div class="achieve block"></div>
                            <div class="achieve block"></div>
                            <div class="achieve block"></div>
                            <div class="achieve block"></div>
                        </div>

                        <h3>Favourite games</h3>
                        <div id="listFavGames">
                            <div class="scroll1">
                                {% for post in favourite_post.all %}
                                    <div class="gameItem">
                                        <a href="{% url 'post:detail' post.pk %}" style="text-decoration: none">
                                            <img src="{{ post.image.url }}" title="{{ post.title }}">
                                            <p>{{ post.title }}</p>
                                        </a>
                                    </div>
                                {% empty %}
                                    <h6 class="empty">No Favourite Games</h6>
                                {% endfor %}
                                <button id="slideLeft1" type="button" style="float: left"><<</button>
                                <button id="slideRight1" type="button" style="float: right">>></button>
                            </div>
                        </div>

                        <h3>My Games</h3>
                        <div class="scroll">

                            <div id="userPosts">
                                {% for post in user_posts %}
                                    <div class="gameItem">
                                    <a href="{% url 'post:detail' post.pk %}" style="text-decoration: none">
                                        <img src="{{ post.image.url }}" title="{{ post.title }}">
                                        <p>{{ post.title }}</p>
                                    </a>
                                    </div>
                                    {% empty %}
                                    <h6 class="empty">No Games. Do you want to <a href="{% url 'post:add-post' %}" class="blinking">upload</a> game?</h6>
                                {% endfor %}
                            </div>

                            <button id="slideLeft" type="button" style="float: left"><<</button>
                            <button id="slideRight" type="button" style="float: right">>></button>
                        </div>


                    <br>
                        <a href="{% url 'post:add-post' %}" style="margin-left: 4%" title="Add Game">
                            <button id="editProfile">Add Game</button>
                        </a>
                    </div>
                </div>

        <script>
            const buttonRight = document.getElementById('slideRight');
            const buttonLeft = document.getElementById('slideLeft');

            buttonRight.onclick = function () {
              document.getElementById('userPosts').scrollLeft += 50;
            };
            buttonLeft.onclick = function () {
              document.getElementById('userPosts').scrollLeft -= 50;
            };
        </script>


		</main>
{%  endblock %}

templates/base.html
<!DOCTYPE html>
{%  load static %}
<html>
	<head>
		<meta charset="UTF-8">
		<title>main</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Baloo+Thambi|Bungee|Cuprum|Fredoka+One|Knewave|Monda|Monoton|Permanent+Marker|Press+Start+2P|Righteous&display=swap" rel="stylesheet">

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

		<style>
			body{
				background-image: url({% static 'images/space.gif'%});
			}
			@media screen and (min-height: 800px) {
			  .sidenav {padding-top: 30px;}
			  .sidenav a {font-size: 18px;}
			}
            button{
                font-family: 'Press Start 2P', cursive;
                color: #c8deff;
            }
            ul {
                list-style: none;
                font-family: 'Monoton', cursive;
            }
            .navitem ul{
                list-style: square;
            }
            .username button{
                float: right;
                display: inline-block;
                font-size:20px;
                margin: 10px;
                font-family: 'Press Start 2P', cursive;
                color: #c8deff;
                border: none;
                background-color:rgba(219, 47 , 0, 0);
            }
            .dropdown {
                position: relative;
                display: inline-block;
            }
            .username{
                position: relative;
                display: block;
                float: right;
                border-radius: 30px;
                border: 3px solid rgba(219, 47 , 0, .5);
                background-color: rgba(219, 47 , 0, 0.8);
                text-align: center;
                margin: 15px;
            }
            .dropdown:hover .dropbtn {
                float: none;
                font-size:25px;
            }
            .dropdown-content{
                display: none;
            }
            .dropdown-content:hover{
                display: inline-block;
            }
            .dropdown-content a {
                font-size:16px;
                margin-top: 10px;
                font-family: 'Press Start 2P', cursive;
                color: #c8deff;
                text-decoration: none;
            }
            .username a{
                font-family: 'Press Start 2P', cursive;
                padding: 10px 0;
                color: #c8deff;
                text-decoration: none;
            }
            .username a:hover{
                animation:blinker 1.2s linear infinite;
                color: #a59fdd;
            }
            .navitem a{
                margin: 0;
                padding: 0;
            }

            .item{
                display: inline-block;
                margin-bottom: 10px;
            }
            .tagItem{
                display: inline-block;
                border-radius: 20px;
                padding: 0 3px;
                margin: 3px;
                background-color: rgba(130, 197, 209, 0.9);
            }
            .tagItem a{
                color: #c8deff;
                margin: 0 5px;
                font-family: 'Fredoka One', cursive;
            }
            .emptyTag{
                display: block;
                text-transform: bold;
                margin: 100px 100px 100px 24%;
                text-align: center;
                font-family: 'Press Start 2P', cursive;
                text-size: 200%;
                color:  rgba(219, 47 , 0, 1);
            }
		</style>
	</head>
	<body>
		<header>

            <div class="username">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="dropbtn"><a href="{% url 'accounts:user' %}">{{user.username}}</a></button>
                            <ul class="dropdown-content">
                                <li><a href="{% url 'accounts:user' %}">Profile</a></li>
                                <li> <a href="/accounts/login">Change User</a></li>
                                <li><a href="{%  url 'accounts:logout' %}">EXIT</a></li>
                            </ul>
                    </div>
                {% else %}
                 <a href="/accounts/login">Login</a>
                {% endif %}
            </div>

            {% block back %}
            {% endblock %}

			<a href="{% url 'main' %}"><img src="{% static 'images/over.png' %}" class="over" style="display: block; margin-left: 19%; margin-right: auto; width: 62%;"></a>


		<div id="mySidenav" class="sidenav" onmouseenter="openNav()" onmouseleave="closeNav()">
			<!--sidnav--->
		<nav class="navbar">
			<a href="{% url 'main' %}"><img src="{% static 'images/logo.png' %}" style="width: 90%;padding: 10px;"/></a>
			<ul>
				<li>
					<div class="item">
						<div class="search-box">
							<input class="search-txt" type="search" name="search" placeholder="Type to search">
							<a class="search-btn" href="#">
								<i class="fas fa-search"></i>
							</a>
						</div>
					</div>
				</li>

				<li>
					<div class="item blinking"><span class="menu_icon"><img src="{% static 'images/circle.png' %}"/></span><a href="{% url 'main' %}" id="nav1" style="display: none;">MAIN</a></div>
				</li>

				<li>
					<div class="dropdown">
						<div><span class="menu_icon"><img src="{% static 'images/castle.png' %}"/></span><a href="#" id="nav2" style="display: none;">GENRE</a></div>
						<ul class="dropdown-content navitem">
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'action' %}">Action</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'adventure' %}">Adventure</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'arcade' %}">Arcade</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'clicker' %}">Clicker</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'fighting' %}">Fighting</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'logic' %}">Logic</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'rpg' %}">RPG</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'race' %}">Race</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'sport' %}">Sport</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'strategy' %}">Strategy</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'other' %}">Other</a></li>
						</ul>
					</div>
				</li>

				<li>
					<div class="dropdown">
						<div class ="dropitem"><span class="menu_icon"><img src="{% static 'images/game.png' %}"/></span><a href="#" id="nav3" style="display: none;">STYLE</a></div>
						<ul class="dropdown-content navitem">
							<li class="blinking"><a href="{% url 'post:tagged_post' 'multiplayer' %}">Multiplayer</a></li>
							<li class="blinking"><a href="{% url 'post:tagged_post' 'singleplayer' %}">Singleplayer</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'girls' %}">For Girls</a></li>
						    <li class="blinking"><a href="{% url 'post:tagged_post' 'boys' %}">For Boys</a></li>
						</ul>
					</div>
				</li>

				<li>
					<div class="item blinking"><span class="menu_icon"><img src="{% static 'images/cup.png' %}"/></span><a href="{% url 'post:tagged_post' 'best' %}" id="nav4" style="display: none;">POPULAR</a></div>
				</li>

				<li>
					<div class="item blinking"><span class="menu_icon"><img src="{% static 'images/new.png' %}"/></span><a href="{% url 'post:tagged_post' 'new' %}" id="nav5" style="display: none;">NEW</a></div>
				</li>
			</ul>
		</nav>

		</div>
		</header>


            {% block content %}

            {% endblock %}

		<footer>
			<img src="{% static 'images/land.png' %}" style="width: 100%; z-index:1;">
					<div class="col-md-12 text-center">
						<p style=" position: absolute; font-size: 12px; margin: 0 auto; left: 0; right: 0; bottom:1em; letter-spacing: 4px; font-family: 'Fredoka One', cursive;z-index: 4; text-align: center;">Copyright by Ranazh Shakieva and Dana Zharkimbaeva. All rights reserved</p>
					</div>
		</footer>
	</body>

	<script>
		function openNav() {
		  document.getElementById("mySidenav").style.width = "250px";
		  document.getElementById("nav1").style.display = "inline-block";
		  document.getElementById("nav2").style.display = "inline-block";
		  document.getElementById("nav3").style.display = "inline-block";
		  document.getElementById("nav4").style.display = "inline-block";
		  document.getElementById("nav5").style.display = "inline-block";
		  document.getElementById("mainsize").style.width = "90%";
		  document.getElementById("mainsize").style.margin = "0 0 0 10%";
		  }
		function closeNav() {
		  document.getElementById("mySidenav").style.width = "60px";
		  document.getElementById("nav1").style.display = "none";
		  document.getElementById("nav2").style.display = "none";
		  document.getElementById("nav3").style.display = "none";
		  document.getElementById("nav4").style.display = "none";
		  document.getElementById("nav5").style.display = "none";
		  document.getElementById("mainsize").style.width = "100%";
		  document.getElementById("mainsize").style.margin = "0";
		}
	</script>

</html>